name: Build AppImage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 toml

      - name: Build executable with PyInstaller
        run: |
          pyinstaller lsfg-vk-qt-ui.spec

      - name: Strip and compress binary
        run: |
          sudo apt-get update
          sudo apt-get install -y upx
          strip dist/lsfg-vk-qt-ui/lsfg-vk-qt-ui || true
          upx --best dist/lsfg-vk-qt-ui/lsfg-vk-qt-ui || true

      - name: Download linuxdeployqt
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Prune unused Qt plugins to reduce size
        run: |
          PLUGINS_DIR=dist/lsfg-vk-qt-ui/plugins
          find "$PLUGINS_DIR" -type d ! -name platforms -exec rm -rf {} +
          find "$PLUGINS_DIR/platforms" -type f ! -name 'libqxcb.so' -delete || true

      - name: Build AppImage
        run: |
          ./linuxdeployqt-continuous-x86_64.AppImage dist/lsfg-vk-qt-ui/lsfg-vk-qt-ui -appimage -executable=dist/lsfg-vk-qt-ui/lsfg-vk-qt-ui

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: '*.AppImage'
